# Generated by Django 3.2.7 on 2021-09-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('name', models.TextField()),
                ('count', models.IntegerField()),
                ('distance', models.FloatField()),
            ],
        ),
    ]
