# Generated by Django 3.2.7 on 2021-09-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Item',
        ),
    ]
