# Generated by Django 3.2.7 on 2021-09-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_table_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='item',
            table='welbex',
        ),
    ]
